apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ci-cd-pipeline
  template:
    metadata:
      labels:
        app: ci-cd-pipeline
    spec:
      containers:
      - name: ci-cd-pipeline
        image: shivamsoundale765/ci-cd-pipeline:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ci-cd-pipeline-service
spec:
  selector:
    app: ci-cd-pipeline
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort

